/caminho/para/linux-challenge/logs/*.log {
    weekly
    rotate 4
    compress
    delaycompress
    missingok
    notifempty
    create 0640 root devops
    dateext
    dateformat -%Y%m%d
    postrotate
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] Log rotacionado." >> /caminho/para/linux-challenge/logs/backup.log
    endscript
}
